### ISSUE TITLE
Cameras Do Not Import Focal Length Keyframes

### ISSUE THREAD

**Issue by KingKong19100** [xavier150/Blender-For-UnrealEngine-Addons#101] opened 2021-06-22 22:17 UTC
I followed the method in the video tutorial (https://www.youtube.com/watch?v=Xx_9MQu2EkM) and the camera animations focal length keyframes were not imported, so there is no zooms on my camera animations.

![Screenshot (171)](https://user-images.githubusercontent.com/75760738/123008161-3b9e6900-d36f-11eb-9365-13f86b0b52dc.png)

**Comment by xavier150** [comment] 2021-06-22 22:39
Hey @KingKong19100 you can send my the file? xavierloux.loux@gmail.com Il will try to found why that don't work.

**Comment by KingKong19100** [comment] 2021-06-22 22:50
Zip File For Project: [Godzilla (2021) Vs Rodan [UE4 Test].zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/6697805/Godzilla.2021.Vs.Rodan.UE4.Test.zip)

**Comment by xavier150** [comment] 2021-06-23 01:11
Hey @KingKong19100 ,
Thanks for the file! I was not able to reproduce the error, that work fine on my side. 
Maybe you don't use the last version. You can check?

![image](https://user-images.githubusercontent.com/7216958/123013878-53084100-d3c5-11eb-9cbf-ccf836655cb9.png)

Oh by the way, I noticed that the export takes a long time, I optimized the addon for bake and export only the necessary keys. 
That should take a lot less time now.
You can try the dev Branch: https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch

**Comment by xavier150** [comment] 2021-06-27 16:37
Hey @KingKong19100 ,
If all work good now you can close this issue too.

**Comment by KingKong19100** [comment] 2021-07-01 19:41
> Hey @KingKong19100 ,
> If all work good now you can close this issue too.

Hey @xavier150, I am so sorry about that! I just got to updating Blender as well as the add-on you sent, and it works amazingly! Thank you so much!!!!

**Closed** 2021-07-01 19:41 UTC
