### ISSUE TITLE
batch Export hidden Collections as an objects produces 5 kb files

### ISSUE THREAD

**Issue by koloved** [xavier150/Blender-For-UnrealEngine-Addons#165] opened 2022-10-31 00:45 UTC
that 5 kb files not contain anything 

when i am working on like 10 objects , i have to unhide objects in collections  every single time when i need to reexport them, so that is kind of uncomfortable

can it be changed so that the selected collections in the export are automatically shown for the export and then hidden? thanks

**Comment by YaraslavR** [comment] 2022-11-02 12:58
Hello, faced the same problem.
When working with multiple objects, I have to display all objects, which is inconvenient.
It would be convenient if they were included when exporting or included together with selecting them in the collection list

**Comment by xavier150** [comment] 2023-01-05 18:11
Hello, Thanks for the report! 
I was not able to reproduce the issue, on my side collections hidden or not the file is bigger than 5kb and the meshe is correct. You can send me an exemple file?

**Comment by koloved** [comment] 2023-01-06 14:40
Hello! thanks for your help! 
I double checked and its working for usuall tree, but if you ll export collection from another collection its produce 5kb file
[export_5kb_issue.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/10360776/export_5kb_issue.zip)

**Comment by xavier150** [comment] 2023-01-09 19:10
Hello, thanks for the file and report! 
I understand and I fixed the issue in the last Dev Branch 

I will close this issue after the update release.

You can try the last dev branch here: https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch

**Closed** 2023-02-10 07:33 UTC
Labels: R Major, R Fixed!
