### ISSUE TITLE
Export recursive doesn't include collision shapes on children

### ISSUE THREAD

**Issue by Avolendi** [xavier150/Blender-For-UnrealEngine-Addons#120] opened 2021-08-21 14:27 UTC
Bug:
When I use Export Recursive, then collision shapes applied to children are not imported into UE4.
I can see the shapes when viewing the fbx file, but in UE4 they have disappeared. Using 'show collision' also confirms they are not there.

Since I have manually defined the collisions, I have Auto Generate Collision turned off.

Using Blender 2.91.0, tool version 0.2.9 Release

**Comment by xavier150** [comment] 2021-08-23 14:44
Hey @Avolendi !
I was not able to reproduce the bug, You can send me the file ? I will try to found what wrong.
You use what version of Unreal?

**Comment by Avolendi** [comment] 2021-08-23 18:27
I'm using Unreal Engine 4.25.4.
Which I am not bound to, so if switching versions fixes it, that would also work for me.
Hadn't tested different version of UE4 yet.

I've create and confirmed it happens with an example project.
I've included the blend and export fbx files in the zip file.

[20210823_CollisionHierarchyExample.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/7034046/20210823_CollisionHierarchyExample.zip)

**Comment by TrillNeato** [comment] 2021-08-23 18:56
In the export, for whatever reason, the mesh is being renamed with '.001' at the end. The way everything's laid out should work as expected but the export is adding .001 to the names of GateA and GateB.

If you remove the '.001' from the mesh name the collision objects are recognized
![image](https://user-images.githubusercontent.com/7545197/130501824-ebe59069-b142-4168-93d8-3fb42e021061.png)

**Comment by Avolendi** [comment] 2021-08-23 19:02
Weird, but good to know.

Ah nice, then I'll try that, since the actual project is a bit big and I'd rather avoid risking typo's ^^;
I update the topic and let you know if that fixes it

**Comment by Avolendi** [comment] 2021-08-23 20:29
SWEEEET.

Ahem.

Yup, so using the latest release ( Rev 0.3.0 - Preview 1 ) solves this problem.
Should I close the ticket, or will you do that after 0.3.0 becomes released?

Thank you very much ^^

**Comment by xavier150** [comment] 2021-08-24 15:19
Thanks @TrillNeato  for the help! ^^
@Avolendi I close this ticket, I will release version 0.3 in not too long I think.

**Closed by xavier150** 2021-08-24 15:19 UTC
Labels: bug
