### ISSUE TITLE
Blender for UE4 0.2.8.0 crashes blender during mesh export. Blender 2.92.

### ISSUE THREAD

**Issue by Sutorcen** [xavier150/Blender-For-UnrealEngine-Addons#92] opened 2021-04-28 17:03 UTC
The add-on has been working fine, ever since I bought it, up until I installed blender 2.92. Now out of the blue when exporting it crashes.

This is what I've done till now and how the crash happens:

I can work on a project for days without it crashing, and out of the blue it will start to crash every single time no matter what or how I export it.

- At first I thought it's a specific mesh. Moved that mesh to a new file. It exports just fine with the add-on.
- Moved the entire project to a new file, with a new name. Worked fine for two days, third day when I tried to export a mesh, it always crashes and there is no way to fix it, unless I move the entire project to a new file with a new name.
- Tried opening the same project to 2.83 (with the same add-ons installed) and it works without an issue.

**Comment by xavier150** [comment] 2021-05-04 17:35
Hey @Sutorcen ,
Thanks for your patience, I just saw your issue I did not receive the notification.

You can send me the crash report? https://docs.blender.org/manual/en/latest/troubleshooting/crash.html
And if you can the .blend file with the crash.

**Comment by Sutorcen** [comment] 2021-05-10 17:51
Hey @xavier150 


> Thanks for your patience, I just saw your issue I did not receive the notification.

It's ok, happens to all of us. :)


> You can send me the crash report?

Working on it.

> And if you can the .blend file with the crash.

I will try to remove as much as I can from the .blend file and sent it to you, since I can't share its contents as is.

Another thing that happens differently now is that every time I export meshes it takes everything out of local view, forcing me to reselect the meshes I want to work with in local view. Whereas in previous versions, exporting meshes didn't do that. Unless it's a setting I have missed.

**Comment by xavier150** [comment] 2021-05-12 12:11
Hey @Sutorcen 
I confirm that the issue is produced because the .blend is corrupted. My Addon will try to show all collection durring the export and when the collection is opened Blender Crash. After some test I found the corrupted obj. 
Remove "Potion_005b.001" in the Blender File Outliner -> Object and now the export work good!

![Corrupted Potion_005b](https://user-images.githubusercontent.com/7216958/117971897-bc0e8a80-b32a-11eb-89dd-206ec764c7a6.jpg)

About local view this is to avoid export errors because FBX Exporter will export only what is visible in the scene. 
In the next version I will add a function for return to Local view after to export so the process will be invisible like for collections.

**Comment by Sutorcen** [comment] 2021-05-16 22:33
Thank you so much for finding a solution to the file corruption. Is there a way to learn how to locate which part of a file is corrupted, for future reference?

**Comment by xavier150** [comment] 2021-05-16 22:45
On my side I open a new Blend file and append all content (File -> Append) pack to pack from the corrupt file and if Blender Crash that because something in what I append is corrupt. So I can I can import smaller packs until I find what is corrupt.

**Comment by Sutorcen** [comment] 2021-05-16 23:27
Thanks. Thought there was a more speedy way, but this will have to do.

**Closed** 2021-06-08 16:13 UTC
