### ISSUE TITLE
Skeletal Animations with Mesh + Static Meshes Not Importing Into UE4 (Syntax Error)

### ISSUE THREAD

**Issue by KingKong19100** [xavier150/Blender-For-UnrealEngine-Addons#102] opened 2021-06-22 22:47 UTC
I tried to import Skeletal Animations with Meshes (like in the video https://www.youtube.com/watch?v=Xx_9MQu2EkM) as well as tried to import Static Meshes, but I keep getting an error which does not allow for this when importing to UE4.

![Screenshot (170)](https://user-images.githubusercontent.com/75760738/123009240-317d6a00-d371-11eb-9215-c826f20fd6f9.png)

**Comment by KingKong19100** [comment] 2021-06-22 22:49
Zip File For Project: [Godzilla (2021) Vs Rodan [UE4 Test].zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/6697805/Godzilla.2021.Vs.Rodan.UE4.Test.zip)

**Comment by xavier150** [comment] 2021-06-23 01:11
Hey @KingKong19100 ,
Thanks! As for the cameras I was not able to reproduce the error, that work fine on my side.

I could import the all static mesh. For skeletal mesh you have multiple root bones. After fixing by adding a main root bone that work too for the both Kaijū.
Info about Multiple Root Bones [Doc](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/How-avoid-potential-errors#multiple-root-bones)

![image](https://user-images.githubusercontent.com/7216958/123018535-06c1fe80-d3cf-11eb-839c-0b0fa8e364c8.png)


As for cameras maybe you don't use the last version. You can check?

**Comment by KingKong19100** [comment] 2021-06-24 20:52
Thank you for helping so far! I checked the doc out, but how I would I remove the multiple root bones in the armatures? How did you manage to import the static meshes?

**Comment by xavier150** [comment] 2021-06-24 23:33
For fix the multiple root bones: Add a new bone to the Armature and name it "Root" then attach the other root bones to the new bone.

StaticMesh import does not work?

**Comment by xavier150** [comment] 2021-06-27 16:36
Hey @KingKong19100 !
About multiple root bones I added a auto fix for the next version in Dev Branch. 
That don't fix the physics errors but you can import in Unreal Engine without getting error.
[Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch)

If all work good now you can close this issue.

**Comment by KingKong19100** [comment] 2021-07-01 21:22
> Hey @KingKong19100 ,
> Thanks! As for the cameras I was not able to reproduce the error, that work fine on my side.
> 
> I could import the all static mesh. For skeletal mesh you have multiple root bones. After fixing by adding a main root bone that work too for the both Kaijū.
> Info about Multiple Root Bones [Doc](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/How-avoid-potential-errors#multiple-root-bones)
> 
> ![image](https://user-images.githubusercontent.com/7216958/123018535-06c1fe80-d3cf-11eb-839c-0b0fa8e364c8.png)
> 
> As for cameras maybe you don't use the last version. You can check?

Hey there! So I took your advice and it worked like a charm! Though I do have a question. Is there a way to import the entire scene and keep the correct locations and scale of each mesh? Or are we supposed to do all the rearranging in Unreal?

**Closed** 2021-07-01 21:22 UTC

**Comment by xavier150** [comment] 2021-07-02 23:07
Redirect about lose location and scale: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/issues/107
